version: '3.3'
services:
  db:
    image: mysql:5.7.21
    container_name: datamessie-db
    ports:
      - 3306:3306
    networks:
      - datamessie
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./datamessie-core/src/conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/db:/var/lib/mysql
  webapp:
    build: ./datamessie-core
    container_name: datamessie-webapp
    ports:
      - 8080:8080
    networks:
      - datamessie
    volumes:
      - ./datamessie-core/src/conf/datamessie.base.properties:/usr/local/tomcat/conf/datamessie.base.properties
      - ./datamessie-core/src/conf/datamessie.processing.properties:/usr/local/tomcat/conf/datamessie.processing.properties
      - ./datamessie-core/src/conf/datamessie.rss.properties:/usr/local/tomcat/conf/datamessie.rss.properties
      - ./datamessie-core/src/conf/datamessie.statistics.properties:/usr/local/tomcat/conf/datamessie.statistics.properties
      - ./datamessie-core/src/conf/datamessie.sync.properties:/usr/local/tomcat/conf/datamessie.sync.properties
      - ./datamessie-core/src/conf/datamessie.view.properties:/usr/local/tomcat/conf/datamessie.view.properties
      - ./data/download:/tmp/download
    depends_on:
      - db

networks:
  datamessie:
