version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: datamessie-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql
